### PR TITLE
reduced gradle build time

### PR DESCRIPTION
**Pull request by DravitLochan**

### CODE REVIEW

**Comment by DravitLochan** [comment]
@opticod please merge this. I'll pr the another one as soon as this get's merged! 
Sorry for delay.

**Comment by DravitLochan** [comment]
@croozeus  please review so that i can proceed with further prs. 
thanks

**Comment by opticod** [comment]
@DravitLochan , Thanks for the PR. We will be reviewing and merging it shortly. Thank you for the patience.

**Review by opticod — APPROVED** [review]
Thanks @DravitLochan :tada:

**Pull request merged**
