### PR TITLE
TemplateEditor activity improved

### PR DESCRIPTION
**Pull request by m-murad**
Made the requested changes to PR #264

### CODE REVIEW

**Comment by free4murad** [comment]
@opticod 
Please check this PR.

**Comment by free4murad** [comment]
@opticod 

What I have implemented in this PR - 

1. If the user starts a new project from `TemplateActivity` and presses back key
    a) If no questions have been added then the project is discarded.
    b) If questions are added but Project Name and Author Name are empty it shows error on the respective edit text.
    c) If all the details are fine, then the user is shown the following dialog box
88398d44-d640-403f-abed-2f542f9650aa
    Each button performs the said task.

2. If the user opens a Draft and presses back key
    a) If all the details are valid the draft is saved
    b) If the ProjectName and AuthorName are null then appropriate error is shown on the EditText.
    c) If no question is present, the user is shown the following dialog box
104632bf-9c91-4902-89ba-3cd44e6ee69f
    Each button performs the said task.

3. If the user opens an existing Project and presses back key
    a) If all the details are valid the draft is saved
    b) If the ProjectName and AuthorName are null then appropriate error is shown on the EditText.
    c) If no question is present, the user is shown the following dialog box
723b11f6-85d6-40df-be8e-9e6c58505174
    Each button performs the said task.


Please review the PR.
Regards

**Comment by opticod** [comment]
@free4murad , Thanks for the PR, will review it soon.

**Review by opticod — CHANGES_REQUESTED** [review]
@free4murad, I tested it. It's better than your last implementation but have the following issues:
- For saving a project as a draft, template name should not be mandatory.
- Making any changes in a draft, should not create a new draft item on saving.
- In templates containing meta details, if there is no questions, then it could be saved as a draft but not as project. Presently it doesn't allows to save as draft.
- In templates containing meta details, if we initially add meta details and add few questions, then remove the meta details. Now, we can't save it as draft. And while saving it as project, it is showing "Enter atleast one question" but it should show "Please enter meta details"
-  If in any saved project, remove the template name or author name, and press back, it crashes!

Optional
- If from any saved project we remove some questions, then it may not be saved as project but can be saved as draft.

**Comment by opticod** [comment]
Are you working on this? U can break this feature into small atomic sub parts, so that we can merge your workable parts and create separate issues for the left ones. Thanks.

**Pull request closed without merging**
