### PR TITLE
Skip tutorial button on every page.

### PR DESCRIPTION
**Pull request by free4murad**
@opticod 
Enhanced PR#238 as requested in issue #224 
Skip tutorial button is on all tutorials except the last one.

### CODE REVIEW

**Comment by opticod** [comment]
@free4murad, make sure you add your commit's user email-ID in ur github info, else you will not be shown in the contributor list by Github.
screenshot from 2016-12-05 23-13-30

**Comment by free4murad** [comment]
@opticod 
Thanks for pointing this.
I have fixed this,can you please verify.
Also should I send a new PR.

**Comment by free4murad** [comment]
@opticod 
can you please verify if my account email id is verified.

**Comment by opticod** [comment]
Yes, it looks like they are verified this time and you will be added to the list once we merge our **bug-fixes** brach to **master** branch.

**Comment by free4murad** [comment]
@opticod 
thanks

**Pull request merged**
