### PR TITLE
Fixed number of toasts if two or more options in Quiz Template are same.

### PR DESCRIPTION
**Pull request by shikharbhuddi**

### CODE REVIEW

**Comment by opticod** [comment]
@shikharbhuddi , can you please add some more info on what you fixed here? And  It looks that you have created the PR targeted to master branch. Can you please redirect to bug-fixes branch.

**Comment by opticod** [comment]
#336

**Comment by m-murad** [comment]
@opticod Can I work on this if @shikharbhuddi not working on it?

**Comment by shikharbhuddi** [comment]
@opticod Apologies for the delay. Missed previous mail. @free4murad I have created the PR.

**Review by opticod — APPROVED** [review]
@shikharbhuddi Thanks... :tada:

**Pull request merged**
