### PR TITLE
[Replaced] existing afollestad's dialogs with dialogs from support library

### PR DESCRIPTION
**Pull request by ishaan1995**
As per the requirement of Issue https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/issues/165, 
changes made are as follows ->
1.Afollestad's dialogs replaced with dialogs from support library with material design styles.
2.Made other changes as per required after removing the dependencies

### CODE REVIEW

**Comment by ishaan1995** [comment]
Hey i have worked on the above(points 2-8), but regarding material design dialog specs, do you need me to change the XML(layout margins and padding) or have appropriate padding while creating the custom dialog?
Need a little help in these guidelines, can you help?

**Comment by opticod** [comment]
I want you to follow this padding guidelines. If you see your present implementation, then you will find them missing. Also make sure the title, content and buttons of the dialog box looks like this : 
screenshot from 2016-11-07 14-45-01

**Comment by opticod** [comment]
@ishaan1995  You again missed few points but I made those changes here and MERGING :tada: : . Overall its was a good effort by you. Thank you. Hope you contribute more. :smile:

**Comment by opticod** [comment]
Make sure from next time you make PR to **bug-fixes** branch. This time I manually merged your commit to it. You can see your commit here https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/commit/b24af7709f316fc6bd61f07e6015634ebe80d458 and log : https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/commits/bug-fixes

**Pull request closed without merging**
