### PR TITLE
Fixed issue #273

### PR DESCRIPTION
**Pull request by vishwesh3**
Fixed issue #273

videotogif_2016 12 12_20 16 20

### CODE REVIEW

**Comment by opticod** [comment]
@vishwesh3 make sure you add your commit's user email-ID in ur github info, else you will not be shown in the contributor list by Github.
screenshot from 2016-12-12 20-47-22

**Comment by vishwesh3** [comment]
Thanks @opticod. I have corrected my emails. Thanks a lot.

**Comment by opticod** [comment]
@vishwesh3, It looks like u have'nt yet corrected it.

**Comment by vishwesh3** [comment]
`git config --get user.email` is giving my correct email id vishwesh03071998@gmail.com
I am new to git, github. Can you please tell me what else I have to do?

**Comment by opticod** [comment]
go to your github profile 's settings and add your email-id there.

**Comment by vishwesh3** [comment]
I have already added vishwesh03071998@gmail.com to github account.

**Comment by vishwesh3** [comment]
Anything else?

**Comment by opticod** [comment]
Oh I see...then Github will recognise your future commits.

**Comment by vishwesh3** [comment]
ok Thanks

**Pull request merged**
