### PR TITLE
Fixed: Issue #9, #20 Delete functionality Added for all Templates

### PR DESCRIPTION
**Pull request by opticod**
Fixed: Issue #9, #20.
Here is the animated video of the  delete feature added for every template.
bug

@batraabhishek Please review. Thank You.

### CODE REVIEW

**Comment by shreyas29** [comment]
According to me, your solution is adding redundancy to delete functionality. Because there is no need to go in Edit option and then delete the question as you can directly delete the question using two options shown in the screenshot below with red circle.

o_9462f77bd53ab8f7-0

**Comment by opticod** [comment]
right, the solution is : either to remove the delete option from toolbar or do add the missing functionality to the delete click of dialog box (presently delete button is there but is not working),hence I thought of adding its functionality..I am waiting for the response from the owners, I will modify it accordingly to their choise .

**Comment by croozeus** [comment]
I think we can just have Cancel in the dialog rather than Delete. The dialog should be dismissed on pressing Cancel and the Item not added.

**Comment by shreyas29** [comment]
@croozeus I did the same thing as you suggested in your comment #30

**Comment by opticod** [comment]
@croozeus ,As suggested by you,I have made changes. Here is some screenshot of it.


screenshot_20160217-191317
screenshot_20160217-191246

**Pull request closed without merging**
