### PR TITLE
Update README.md

### LINKED ISSUE #452: Resize the screenshots in the documentation
The sizes of sceenshot in documentation can be fixed such that all the screenshots have same widths and heights.

I would like to work on this issue. 
@opticod @croozeus Can I proceed?

### PR DESCRIPTION
**Pull request by Rimjhim28**
Fixes #452 , the widths, heights and appearance ( changed to table view ) in the documentation.

### CODE REVIEW

**Comment by opticod** [comment]
Please redirect your PR to `bug-fixes` branch as mentioned in README.md

**Comment by Rimjhim28** [comment]
@opticod Done!

**Review by opticod — APPROVED** [review]
LGTM. Thanks for this PR.  🎉

**Review by Rimjhim28 — COMMENTED** [review]
The PR was to resize and organize the screenshots

**Pull request merged**
