### PR TITLE
Changed variable names to lowerCamelCase. Fixes #328

### LINKED ISSUE #328: Variable naming conventions in Java
Many classes are having variable names in lower case with hyphens. Shall I mind changing them to `lowerCamelCase` (according to Java Conventions)?

### PR DESCRIPTION
**Pull request by yadav-rahul**
Many classes were having variable names in lower case with hyphens, as stated in #328 .

 This PR changes them to `lowerCamelCase` which is standard convention for naming variables in Java.

### CODE REVIEW

**Comment by yadav-rahul** [comment]
@croozeus @opticod Please review changes done in this PR.

**Comment by yadav-rahul** [comment]
@croozeus @opticod Please check this PR and suggest changes.

**Comment by opticod** [comment]
@yadav-rahul It looks that you have created the PR targeted to master branch. Can you please redirect to bug-fixes branch.

**Comment by yadav-rahul** [comment]
@opticod Done.

**Pull request merged**
