### PR TITLE
Fixed option duplicacy in match template list and metadata delete issue in Comprehension and MatchTemplate issue

### PR DESCRIPTION
**Pull request by free4murad**
Fixed issue #326 

@opticod please review the PR.

### CODE REVIEW

**Comment by opticod** [comment]
@free4murad, please wait for reviews before creating PRs. Suggested some changes in : https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/issues/355

**Comment by free4murad** [comment]
@opticod 
please review this.
will solve issue #355 in another PR.

**Comment by opticod** [comment]
@free4murad, ok we can merge this because redundancy is fixed here. Reviewing.

**Comment by free4murad** [comment]
@opticod 
should i make the changes in this PR or remove the commit for #329 from this PR?

**Comment by opticod** [comment]
Its always suggested, that in one PR, fix only a single issue.

**Comment by free4murad** [comment]
@opticod 
please review

**Pull request merged**
