### PR TITLE
Skip tutorial button added.

### PR DESCRIPTION
**Pull request by free4murad**
Solved issue #224

### CODE REVIEW

**Comment by free4murad** [comment]
@opticod 
I have deliberately kept it that way.
Skip tutorial button usually appears only the first time user installs the app (if the user is in a hurry and just wants to get the work done).The app is implicitly showing the tutorial.
But later on the user is explicitly viewing the tutorial, there is no point of adding skip button there.

Should i keep it this way or

**Comment by opticod** [comment]
Seems logical. Thanks @free4murad ..Merging

**Comment by free4murad** [comment]
@opticod 
Should I make a new PR just push changes to this one?

**Comment by opticod** [comment]
You have to create a new PR. @free4murad

**Pull request merged**
