### PR TITLE
Timer not stops in background solved

### PR DESCRIPTION
**Pull request by codingblazer**
#342 I am cancelling the timer in onPause and creating new from same time left in onResume().Will be sending PR in templates repo too.

### CODE REVIEW

**Comment by iit2014086** [comment]
@codingblazer  why not add a pause button too?

**Comment by codingblazer** [comment]
@iit2014086 Thanks for suggestion. 
Comprehension is supposed to be a test and will undermine the purpose if we add pause button. As for some things like, phone calls, Whatsapp message, etc , the timer should pause because these are uninvited. 
However if mentors feels like adding button for pause I will add it :-)

**Comment by sm86** [comment]
Being a test, I don't thnk we should even stop the timer in the background. The person may give a pause(make a call to get answer, WhatsApp )and answer.

**Comment by iit2014086** [comment]
Yeah I too feel it's best we leave the timer running. The user may intentionally press the home button so as to make the timer stop.

**Comment by croozeus** [comment]
@codingblazer thanks for the PR. Looks good to me - @opticod we should merge it once we make the release today or tomorrow.

**Comment by codingblazer** [comment]
@croozeus Thanks.
@sm86 By test I meant , students will be using this for self assessment. Why will student make a call just to stop the timer if he can just close and restart to do the same. From what I know, use case of app is to help students assist them in competitive exams to assess them.

**Comment by iit2014086** [comment]
@codingblazer yeah but he can take a screenshot. Anyway, if the user does that kind of thing, we can consider it to be his loss.

**Comment by opticod** [comment]
@codingblazer , @croozeus While building the system, I had intentionally kept the timer running in background, because in online completions or in any quiz we can't pause or stop the timer. We need to finish it in mentioned time irrespective of if we take any breaks. 

If we want, we can add the pause-able feature. This requires modifications at the user data. We should ask the mentor if he wants the users to have the facility of pausing the timer or not. If yes, then the user's timer will be paused on activity stand-by, else it will keep on running. 

@croozeus @codingblazer , Give your views on this.

**Comment by opticod** [comment]
One more idea is to preventing test-takers from going out of the window focus, so that test's genuinity is maintained.

**Comment by croozeus** [comment]
@opticod well, I don't think we should give a pause button. It's a test so we shouldn't allow the student to pause the timer. That being said, if for whatever reason the app goes into the background - like for example a call, etc. then we should pause the timer and restart again. I don't think students will misuse this.

**Comment by codingblazer** [comment]
@opticod @croozeus I think asking the mentor while creating apk as suggested by @opticod can be good option seeing different views on this issue. However personally I think timer should be paused when app goes in background.
@opticod @croozeus So,should I make any changes ?

**Comment by codingblazer** [comment]
@opticod Can we merge it ? Thanks

**Comment by opticod** [comment]
Will soon start reviewing and merging the PRs. Thanks.

**Pull request merged**
