### PR TITLE
load only buildmlearn generated apks

### PR DESCRIPTION
**Pull request by iit2014086**
before in loadapkfragment all the apks present in downloads directory is displayed....now it displays only those genereated by buildmlearn

### CODE REVIEW

**Comment by croozeus** [comment]
Please also provide a detailed description of what this PR contains.

**Comment by croozeus** [comment]
@opticod please check and merge

**Comment by iit2014086** [comment]
checks got passed in codacy but results are not being updated on github

**Comment by opticod** [comment]
LGTM, merging :+1: Hopefully you will contribute more :smile:

**Comment by iit2014086** [comment]
Definitely!!! Thanks for the merge  :smile:

**Pull request merged**
