### PR TITLE
<#Issue 5><Addition of a Create Project in Saved Projects>

### LINKED ISSUE #5: Saved Projects Screen Improvements
In my opinion if there are no saved projects, a message should be displayed indicating the user does not have any saved projects yet, and if need be directed to creating a new project option.

### PR DESCRIPTION
**Pull request by octacode**
# If the Saved Projects fragment is empty. Then the user can be redirected to the Template Activity by the push of a button. fixes #5

[https://drive.google.com/file/d/0B3goqm-HUlJvSVc5dHFuOVlrTlU/view?usp=sharing](https://drive.google.com/file/d/0B3goqm-HUlJvSVc5dHFuOVlrTlU/view?usp=sharing)
@opticod 
Will this image do? Thanks.

### CODE REVIEW

**Comment by octacode** [comment]
[https://drive.google.com/file/d/0B3goqm-HUlJvSVc5dHFuOVlrTlU/view?usp=drivesdk](url)
Sorry for the above link.

**Comment by octacode** [comment]
The link is not working directly. You can copy and paste the URL on the address bar. It will work then.
Thanks

**Comment by opticod** [comment]
Thanks for the image. We are reviewing. 

Looks like u are making multiple fixes in a single branch.
Suggestion:
1. Solve different issues in different PRs.(  If you are working simultaneously in more than one issues, make sure made those changes in your different branches. Try making a branch from bug-fixes for every issues and then make changes there. With those changes make PRs to our bug-fixes branch. And after getting merged, always update your bug-fixes branch and again start with a new branch for new issues.)

**Comment by octacode** [comment]
Thanks @opticod :)

**Comment by croozeus** [comment]
I think redirecting the user to create project is a good idea when there are no saved projects. However, let's not have the tick image - it doesn't indicate emptiness. The text should be just fine "No saved items yet".

Also, rather then having a "Create Project" link - I would prefer an FAB for creating a new project. So please replace the link with FAB on the right bottom corner.

**Comment by octacode** [comment]
Thanks. I will make the changes.

**Comment by octacode** [comment]
Okay...I will change text to a Floating Button.Thanks

**Comment by opticod** [comment]
@octacode , It looks that you have added duplication of commits here. 1cc5440 is same as that in your PR #185

**Comment by octacode** [comment]
@opticod 
Hey! I have added a shaking effect on the Floating button in the commit. While I have added the animation of bouncing up on the First run activity in the FirstRunActivity.
If still there's something you don't find right. Please suggest me the changes.

**Comment by octacode** [comment]
Here's how the SavedProjectsFragment is looking like.
[Video Link](https://www.youtube.com/watch?v=qpDDBrUhxdQ)

**Comment by opticod** [comment]
@octacode 

1. Increase the font size little bit to that of ```?android:textAppearanceMedium```
2. Its better to remove the shaking effect, as it may be disturbing to users.
2. Replace the tick symbol in ```Saved APKs``` and ```My Drafts``` too with proper text messages.

**Comment by octacode** [comment]
Great! I will make the changes.

**Comment by croozeus** [comment]
@opticod thanks for reviewing. Let's merge this.

**Comment by octacode** [comment]
@croozeus
@opticod
Thanks for the merge :)

**Pull request merged**
