### PR TITLE
added metacafe video support for videocollectiontemplate

### PR DESCRIPTION
**Pull request by iit2014086**

### CODE REVIEW

**Comment by opticod** [comment]
@iit2014086 , you also need to make changes in the template files and in its simulator.
Template files : https://github.com/BuildmLearn/Toolkit-mobile-templates
Simulator files : in current repo

**Comment by iit2014086** [comment]
@opticod  i added necessary changes in toolkit-mobile-templates...can you tell me the reason for conflicts..couldn't figure it out...

**Comment by opticod** [comment]
Try to rebase with the current **bug-fixes** branch. If you face any problem then let me know.

**Comment by opticod** [comment]
Can you please squash your commits?

**Comment by iit2014086** [comment]
yeah trying to do that...i didnt know that merge commits wont be shown in rebase

**Comment by iit2014086** [comment]
@opticod  closing this pr...created a new one here https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/pull/267...please check it.

**Pull request closed without merging**
