### PR TITLE
Making the delete Temperory files AsyncTask

### PR DESCRIPTION
**Pull request by octacode**
Fixes Issue : #178

### CODE REVIEW

**Comment by octacode** [comment]
Thanks, I will make the changes

**Comment by octacode** [comment]
@opticod
Hey! Would it be fine to show a progressDialog with the message "Deleting Temporary Files"in the preExecute() and an AlertDialog Box showing the completion of process in the postExecute() of the AsyncTask class.

**Comment by opticod** [comment]
Yes, u can

**Comment by octacode** [comment]
Great.

**Comment by octacode** [comment]
Accidentally I deleted the branch so I really am sorry for the second commit.
Thanks

**Comment by octacode** [comment]
Thanks for the merge.

**Pull request merged**
