### PR TITLE
Simplifying Navigation Drawer

### PR DESCRIPTION
**Pull request by chiragw15**
Solving Issue #190 and #180. Things implemented : 
1.) Added Navigation Drawer from Support Library.
2.) Removed complex Navigation Drawer.
3.) Made new threads to Load Projects and APKs.
4.) Solved issue #180. Now pressing back button goes to home fragment rather than to previous fragment.

### CODE REVIEW

**Comment by chiragw15** [comment]
@opticod changes done. But there is a merge conflict. Can you please help me with that?

**Comment by opticod** [comment]
@chiragw15 Try to rebase your forked branch with the current **bug-fixes** branch.

**Comment by chiragw15** [comment]
@opticod done. Thanks :)

**Comment by opticod** [comment]
LGTM! Awesome, passed all codacy+travis test , Merging. :tada:

**Pull request merged**
