### PR TITLE
updated gradle for directly running the code after cloing the repo

### PR DESCRIPTION
**Pull request by ashishg656**
Commit 1 -  (@5c9cc5025a3236457383b533583bc9608182d9c3) : It took me a lot of time in resolving errors due to my support library version being 23,which is latest version whereas the repo is not directly usable with version 23, it gives errors about resource files..

I have made changes to make code compliant with support library version 23, and also updated gradle versions and other gradle related things.

Also, the material dialog library was giving error in gradle sync since it is no longer available through that link.Hence I updated material dialog library gradle version.(jitpack was added due to the new version of material dialog library)

In new version , com.afollestad.materialdialogs.ThemeSingleton was not present. Instead it was moved to com.afollestad.materialdialogs.internal.ThemeSingleton and had minor changes as well which are reflected in TemplateEditor class.

### CODE REVIEW

**Comment by chhavip** [comment]
+1 to all the changes mentioned as similar problems were faced by me while setting up the project

**Comment by ashishg656** [comment]
Commit 2 - (@d4da4ce176c8a44d0035bc2a6e8eeba735c99402) : a bug corrected that was closing force close....
In the TemplateEditor activity, when we remove an added list item using the action bar buttons, it works correctly, but when we remove an item using the cross button in list view item, the action bar menu buttons are not chnaged to simulator and save icon instead stay the same as edit and delete...and when we click on that delete button from the action bar, we get force close..since that view do not exist in list data ....

screenshots of the same are here---
this happens in all templates (info,quiz,card and spelling)

screenshot_2015-12-25-10-31-32
screenshot_2015-12-25-10-31-56
screenshot_2015-12-25-10-32-04

**Comment by yatna** [comment]
@ashish656. I cloned the latest version of this repository and imported the project in android studio. But the project on compilation gives errors as shown in screenshot. Errors are given in styles.xml, values-v21\styles.xml and values-v16\styles.xml. Please help me , I am new to this. Thank You.
styles1

styles1
styles1

Some colors and attributes are present in these files which are not present in resources eg. color/primary_text_material_dark and gives errors. 

It would be really helpful if you can tell me exactly how to import the project so that it can be compiled .

**Comment by ashishg656** [comment]
@yatna : this generally happens due to older versions of android sdk. Please update all your sdks to latest version from the sdk manager of android studio. Disable offline mode. And then build the project again after updating the android sdk.  :) do let me know if you face any problem

**Comment by ashishg656** [comment]
Also you are using a older version of Android studio. I would advice you to update that. You can also try using android studio version 2 (still in preview)  which has got instant run feature that can refresh the activity to reflect changes without restarting complete application.

**Comment by yatna** [comment]
@ashishg656 I updated my SDK. Here is what it looks like now-
sc
Offline mode was already disabled . Then I again imported the project from file->import project and so on. 
import

I chose create project from existing resource. After a few dialog boxes I encountered this one.
ins
I chose android Api 23 platform and the project was imported successfully.
Also on opening this message was shown.
" Migrate project to Gradle? This project does not use the Gradle build system , we recommend you to migrate to the Gradle build system.

However, on compiling it still gives the same number of error and in the same files. :-(
I was facing some problem updating my android studio , and hence could not update it. Is this because of that ? Thanks for your time.

**Comment by ashishg656** [comment]
I also faced some issues in importing the project initially since I hadnt downloaded sdk for api 23. i changed compile sdk version to api 23, downloaded sdk and rebuilt project and it worked. May be its due to old android studio version..

You can try compiling against version 22 but then you will have to change all dependencies to be against version 22.

Have a look at these answers:

http://stackoverflow.com/questions/26530415/error-in-styles-base-xml-file-android-app-no-resource-found-that-matches-the

http://stackoverflow.com/questions/32092511/resource-error-in-android-studio-after-update-no-resource-found

Are you able to compile other applications against version 23?



Screenshot of my sdk manager for your reference.

**Pull request merged**
