### PR TITLE
Spanish language support added

### PR DESCRIPTION
**Pull request by saketkumar95**
I have added the support for Spanish Language [#169](https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/issues/169) . Please Check it.

### CODE REVIEW

**Comment by opticod** [comment]
Hey @saketkumar95 , are you confident with your translation? Is this performed using any google translator ?

**Comment by saketkumar95** [comment]
Yes i'm confident with the translations. I have cross checked it 2-3 times using many google translator.

**Comment by saketkumar95** [comment]
@opticod I'm having some problem with this branch and want to remove. What's the status for this PR?

**Comment by opticod** [comment]
@saketkumar95 I am waiting for the notification from @croozeus

**Comment by croozeus** [comment]
Google translations is not the correct way of doing this. They are good for a start but to merge into master - we'll need couple of native spanish speakers to review this. 

Moreover, at a project level - I think the best way to do translations is to use a crowdsourced service - I'll look more into it this month. 

Closing this for now.

**Comment by saketkumar95** [comment]
Cool. No problem :)

**Pull request closed without merging**
