### PR TITLE
#211 Splash added

### PR DESCRIPTION
**Pull request by codingblazer**

### CODE REVIEW

**Comment by codingblazer** [comment]
Hey @croozeus @opticod , I think there is some problem with Travis CI as

**Comment by free4murad** [comment]
@croozeus  @opticod 
Yes there is some problem with Travis CI.
My PR is also not able to build properly.

**Comment by opticod** [comment]
@codingblazer @free4murad , yaa I too observed it yesterday. I also tried restarting the build but it too failed. Thanks for your solutions. Let me fix it. You all can also help. If it still doesn't work, then we can move to Circle-CI, its more reliable and faster. I too explored it during my GSoC period but it requires some admin permissions to set up @croozeus.

**Comment by free4murad** [comment]
@opticod 
should i make a to migrate the project from Travis to Circle-CI.

**Comment by opticod** [comment]
@free4murad , First we should try solving travis. If it doesn't work, then you can continue.

**Comment by croozeus** [comment]
Regarding problem with Travis-CI - we need to fix this. I would really not move to Circle-CI as Travis-CI is more open source friendly. @opticod can you look into this at priority. Meanwhile, please do not merge any changes that fail the CI checks.

**Comment by opticod** [comment]
Ok sure @croozeus sir, trying to fix travis.

**Comment by croozeus** [comment]
Thanks @opticod If you want you can create an issue for this so that others can discuss, give their suggestions on this.

**Comment by codingblazer** [comment]
@opticod I also considered reusing the first_run_bg.jpg but the problem is -
first_run_bg.jpg doesn't  have "BuildmLearn Toolkit" Text in the image like in mainsplash.jpg and i can't add this text to first_run_bg.jpg using android theme ( I am implementing theme based splash as discussed). If  I have to add text to first_run_bg , I have to create xml to add this text which means purpose of using theme based splash will be ruined as discussed in that article. I even tried creating my own drawable with first_run_bg as bitmap item but no help there. Please tell if you have any solution to this.

**Comment by opticod** [comment]
Merged via d7f0fbd5882075d5c39aed0454d8d68fcd2f71f5 and fa3dc90c9e2031c565cda7d41d6b06b60a88230e

**Pull request closed without merging**
