### PR TITLE
Validations added

### PR DESCRIPTION
**Pull request by codingblazer**
Hey , I have made validations for Template name, Author name and Username (in Settings and FirstRunActivity) to check for empty string or string with non alphanumeric starting character which looks like this now -
device-2016-11-06-080945

### CODE REVIEW

**Comment by codingblazer** [comment]
@opticod Please review the PR. I have resolved the merge conflicts.

**Comment by codingblazer** [comment]
@opticod Very sorry for that. Some things changed up without my knowledge after rebasing. Its been solved now.

**Comment by opticod** [comment]
@codingblazer , Can you please squash your commits into one?

**Comment by codingblazer** [comment]
@opticod Done :)

**Comment by opticod** [comment]
In SettingsFragment, if we did not add any author name, rather than closing the dialog box with no effect, it would be better to give some error message that author name can't be empty

**Comment by codingblazer** [comment]
@opticod I think Toast should be good ?

**Comment by opticod** [comment]
Yes, it will be good, and don't close the dialog box until the input is valid.

**Comment by codingblazer** [comment]
@opticod I have added the Toast. 
As for not closing the dialog - On Clicking Positive OK button, dialog dismisses internally and thus we have to override that internal (show) behavior and then button click on top of it which will bring a lot of complex code in order to do so. However if you want it I will add it to PR.

**Comment by opticod** [comment]
@codingblazer You can check how I implemented it in 39f605a

**Comment by codingblazer** [comment]
@opticod Thanks for reference. This is really a good implementation compared to the one I was thinking ( make custom dialog class overriding show behavior).

**Pull request merged**
