### PR TITLE
Dependencies removed

### PR DESCRIPTION
**Pull request by codingblazer**
I have removed the following external dependencies -

`compile files('libs/pkix-1.51.0.0.jar')`
`compile 'com.cocosw:bottomsheet:1.3.0@aar'`
`compile 'com.nineoldandroids:library:2.4.0'`

### CODE REVIEW

**Comment by opticod** [comment]
Issue #207

**Comment by opticod** [comment]
@codingblazer Aren't u working on this?

**Comment by codingblazer** [comment]
@opticod Yes, I am working on this only. There are multiple merge conflicts from different PR's. Will resolve all of them soon.

**Comment by codingblazer** [comment]
@opticod Please review , i have resolved all conflicts.

**Comment by opticod** [comment]
@codingblazer, Shall we remove this from Dec release or keep it?

**Comment by codingblazer** [comment]
@opticod Feel free to take decision on that. However, I have tested it properly for functioning.

**Comment by opticod** [comment]
@codingblazer , does button selector is working in your case?

**Comment by opticod** [comment]
It seems, that you have just added..Thanks...let me check.

**Comment by codingblazer** [comment]
@opticod Yes, but it is not noticeable because its fast. But its working- Look -
whatsapp image 2016-12-13 at 20 26 05

**Comment by opticod** [comment]
:+1:  @codingblazer, Meanwhile, I was trying to add that ripple effect, now it seems working fine...let me merge yours and add mine implementation.

**Comment by opticod** [comment]
@codingblazer , no need of merge conflict, I have already resolved it...don't push again

**Comment by codingblazer** [comment]
@opticod Thanks

**Pull request merged**
