### PR TITLE
fixed building with latest version of material-dialogs and support lib

### PR DESCRIPTION
**Pull request by championswimmer**
using latest material-dialogs (0.8.5.6)
  and latest Android Support libs (23.2.0)

Signed-off-by: Arnav Gupta <championswimmer@gmail.com>

### CODE REVIEW

**Comment by championswimmer** [comment]
Should fix this issue https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/issues/104

**Comment by championswimmer** [comment]
Also fixed this issue 
https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/issues/96

**Comment by championswimmer** [comment]
@croozeus please take a look. current builds are broken due to incompatibilites with material-dialogs and design-support

**Comment by opticod** [comment]
info_template_detail.xml no more exists in present code. We have removed all unnecessary resources recently. Can you please update this PR?

**Pull request closed without merging**
