### PR TITLE
Fixes #314

### LINKED ISSUE #314: backpress not working properly in simulator of video,dictation and flash templates
Problems in Video and Dictation templates:<br>
            Create a project and run the simulator. Now select a video(or dictation). Click back press. You will be redirected to choose. Instead go to the last fragment and click restart. Now click back press. Instead of redirecting to choose you will be exited.<br>
Problems in flash card template:<br>
            Clicking backpress should take you to the previous card. Instead the app is exiting.

@opticod shall I create a pr for this?

### PR DESCRIPTION
**Pull request by tejavojjala**

### CODE REVIEW

**Review by opticod — COMMENTED** [review]
@tejavojjala, Can you please confirm this PR is updated with latest implemntation in (https://github.com/BuildmLearn/Toolkit-mobile-templates/pull/45)? Along with can you please add one commit updating these : Comprehension, Dictation, Flash Card Template, Info Template, Learn spelling, Quiz template, Video Collectio Template APKs by building from the dev branch in templates-repo.

**Comment by tejavojjala** [comment]
@opticod Sure! Will update the pr.

**Comment by opticod** [comment]
@tejavojjala, b844eb0 is the updated commit right?

**Comment by tejavojjala** [comment]
@opticod yes, it's the updated one.

**Review by opticod — APPROVED** [review]
Thanks @tejavojjala , :tada:

**Pull request merged**
