### PR TITLE
Rearranging Items #352

### PR DESCRIPTION
**Pull request by jainkuniya**
PR addressing issue #352
Now on long pressing items can be rearranged.
videotogif_2017 01 02_19 54 29

### CODE REVIEW

**Comment by opticod** [comment]
@vishwesh3 , Its looking good. Can you implement this feature with the help of touch and dragging?

**Comment by vishwesh3** [comment]
sure, I will update PR soon.

**Comment by vishwesh3** [comment]
Now we can rearrange via drag drop.
now should I remove up down options from menu?
videotogif_2017 01 08_01 38 06

**Comment by opticod** [comment]
Please fix codacy error everytime.

**Comment by vishwesh3** [comment]
Sorry for all this. I am working on it and will create a new PR.

**Comment by vishwesh3** [comment]
Now rearrangement can be done via drag and drop.

videotogif_2017 01 09_17 23 08
videotogif_2017 01 09_17 30 43

**Comment by vishwesh3** [comment]
@opticod done with the touch and dragging.

**Comment by opticod** [comment]
@vishwesh3, Can you please resolve the conflicts and squash your commits into one?

**Comment by vishwesh3** [comment]
sure, will update PR soon :)

**Comment by vishwesh3** [comment]
@opticod Done resolved conflicts and squashed commits into one. :)

**Review by opticod — APPROVED** [review]
Thanks @vishwesh3, It's a really nice featured added by you. Hope you contribute more :) :tada:

**Comment by jainkuniya** [comment]
Thanks @opticod for merging . Me too excited to work on this wonderful project. :)

**Pull request merged**
